python = "3.11"

[tool.black]
target-version = ["py311"]
line-length = 150

[tool.ruff]
line-length = 150
exclude = ["github-submodule"]

[tool.ruff.lint]
select = ["A", "B", "C", "E", "F", "G", "I", "N", "Q", "S", "T", "W",
          "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT",
          "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH",
          "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT",
          # see: https://github.com/charliermarsh/ruff#table-of-contents
]
ignore = [
    "UP007",
    "DTZ001",
    "FBT001",
    "B006",
    "ANN101",
    "S311",
]
exclude = [
    ".git"
]
